In [2]:
import numpy as np
import matplotlib.pyplot as plt

Advance operations with an example data 

In [4]:
np.random.seed(42)

employee_data = np.column_stack((
    np.arange(1, 10001),                  # Employee ID
    np.random.randint(20, 61, 10000),     # Age
    np.random.randint(1, 31, 10000),      # Experience
    np.random.randint(30000, 150001, 10000),  # Salary
    np.random.randint(1, 6, 10000)        # Department ID
))

print(employee_data)

[[     1     58     26 103185      3]
 [     2     48     25 145199      3]
 [     3     34      7 136745      3]
 ...
 [  9998     37     15 141342      4]
 [  9999     46     20  68736      5]
 [ 10000     54     30 107195      4]]
