In [2]:
import numpy as np

Create a list and np_array

In [ ]:
list = [1, 2, 3, 4, 5]
print(list)

np_array = np.array([13, 23, 37, 12, 5])
print(np_array)

Time taken for the same task in list and np_array

In [ ]:
import time

start = time.time()
py_list = [i*2 for i in range(100000000)]
end = time.time()
print(f"Python list creation time: {end - start}")

start = time.time()
np_array = np.arange(100000000) * 2
end = time.time()
print(f"NumPy array creation time: {end - start}")


Vector , Matrix and Tensor

In [4]:
# vector 

vector = np.array([1, 2, 3, 4, 5])
print("Vector:\n", vector)

# matrix

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)

# Tensor

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector:
 [1 2 3 4 5]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Create an array with Dtype 

In [5]:
arr_float = np.array([1, 2, 3, 4, 5], dtype=np.float32)   
print("Array with specified data type:\n", arr_float)
print("Data type of the array:", arr_float.dtype)


arr_int = np.array([1, 2, 3, 4, 5], dtype=np.int32)
print("Array with specified data type:\n", arr_int)
print("Data type of the array:", arr_int.dtype)

arr_complex = np.array([1, 2, 3, 4, 5], dtype=np.complex64)
print("Array with specified data type:\n", arr_complex) 
print("Data type of the array:", arr_complex.dtype)

Array with specified data type:
 [1. 2. 3. 4. 5.]
Data type of the array: float32
Array with specified data type:
 [1 2 3 4 5]
Data type of the array: int32
Array with specified data type:
 [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
Data type of the array: complex64
