In [1]:
import numpy as np

Array properties

In [ ]:
arr = np.array([[1, 45, 32], [28, 7, 76], [23, 56, 89], [12, 34, 56]])
print("Array:\n", arr)
print("Shape of the array:", arr.shape) # gives the shape of the array (number of rows, number of columns)
print("Number of dimensions:", arr.ndim) # gives the number of dimensions of the array
print("Size of the array:", arr.size) # gives the total number of elements in the array
print("Data type of the array:", arr.dtype) # gives the data type of the array
print("Item size (in bytes):", arr.itemsize) # gives the size of each element in the array
print("Total bytes consumed by the array:", arr.nbytes) # gives the total bytes consumed by the elements of the array
print("Transpose of the array:\n", arr.T) # gives the transpose of the array

Array:
 [[ 1 45 32]
 [28  7 76]
 [23 56 89]
 [12 34 56]]
Shape of the array: (4, 3)
Number of dimensions: 2
Size of the array: 12
Data type of the array: int64
Item size (in bytes): 8
Total bytes consumed by the array: 96
Transpose of the array:
 [[ 1 28 23 12]
 [45  7 56 34]
 [32 76 89 56]]


Array Reshaping

In [13]:
arr = np.arange(10)
print("Original array:", arr)

reshaped_arr = arr.reshape(2, 5) # Reshape the array to 2 rows and 5 columns
print("Reshaped array (2x5):\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten() # Flatten the array back to 1D - returns a copy of the array collapsed into one dimension
print("Flattened array:", flattened_arr)

raveled_arr = reshaped_arr.ravel() # Ravel the array back to 1D (returns a flattened view) - returns a flattened view of the array, which is a reference to the original array whenever possible
print("Raveled array:", raveled_arr)

reversed_arr = arr[::-1] # Reverse the array
print("Reversed array:", reversed_arr)

Original array: [0 1 2 3 4 5 6 7 8 9]
Reshaped array (2x5):
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened array: [0 1 2 3 4 5 6 7 8 9]
Raveled array: [0 1 2 3 4 5 6 7 8 9]
Reversed array: [9 8 7 6 5 4 3 2 1 0]


NUMPY properties 

In [14]:
# Zero - By default the dtype of the array is float64

np_zeros = np.zeros((3, 4))
print(np_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
# Ones

np_ones = np.ones((2, 3))
print(np_ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
# full - Create an array filled with a specific value
# parameters: shape, fill_value

np_full = np.full((2, 3), 5)
print(np_full)

[[5 5 5]
 [5 5 5]]


In [17]:
# random.rand - Create an array with random values
# parameters: shape

np_random = np.random.rand(2, 3)
print(np_random)

# random.uniform - Create an array with random float values from a uniform distribution
# parameters: low, high, size

np_uniform = np.random.uniform(1, 10, size=(2, 3))
print(np_uniform)

# random.randint - Create an array with random integer values
# parameters: low, high, size

np_randint = np.random.randint(1, 10, size=(2, 3))
print(np_randint)

[[0.21679476 0.81616739 0.05241223]
 [0.99465053 0.10779135 0.38591785]]
[[2.59342149 2.72420721 6.23661277]
 [2.74931239 3.98857012 6.37828657]]
[[8 3 9]
 [2 3 3]]


In [18]:
# arrange - Create an array with evenly spaced values within a given interval
# parameters: start, stop, step(intervals between values)

np_arange = np.arange(0, 10, 2)
print(np_arange)

[0 2 4 6 8]


Generate large data set using random and pcg

In [ ]:
from numpy.random import Generator as gen, PCG64 as pcg

arr_rg = gen(pcg(seed=42)) # Create a random number generator with a specific seed for reproducibility

arr_rg.normal(size=(2, 3)) # Create an array with random float values from a normal distribution

array([[-0.41931217, -0.04067674,  0.53459886],
       [ 0.68282028,  1.87032793,  1.00822713]])

In [4]:
arr_rg = gen(pcg(seed=42)) # Create a random number generator with a specific seed for reproducibility

arr_rg.integers(1, 10, size=(2, 3)) # Create an array with random integer values between 1 and 10

array([[1, 7, 6],
       [4, 4, 8]])

In [5]:
arr_rg.random(size=(2, 3)) # Create an array with random float values from a normal distribution

array([[0.69736803, 0.09417735, 0.97562235],
       [0.7611397 , 0.78606431, 0.12811363]])