In [1]:
import numpy as np

Slicing 

In [3]:
arr = np.array([12,3334,6,77,78,78,7,8934,3])
print("Array:\n", arr)
print("Basic slicing:\n", arr[1:5]) # gives elements from index 1 to 4
print("Slicing with step:\n", arr[1:8:2]) # gives elements from index 1 to 7 with a step of 2
print("Slicing with negative step:\n", arr[7:1:-2]) # gives elements from index 7 to 2 with a step of -2
print("Slicing with negative indices:\n", arr[-5:-1]) # gives elements from index -5 to -2


Array:
 [  12 3334    6   77   78   78    7 8934    3]
Basic slicing:
 [3334    6   77   78]
Slicing with step:
 [3334   77   78 8934]
Slicing with negative step:
 [8934   78   77]
Slicing with negative indices:
 [  78   78    7 8934]


Indexing

In [5]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("2D Array:\n", arr_2d)

print("Specific element:\n", arr_2d[1, 2]) # gives the element at row 1, column 2
print("Entire row:\n", arr_2d[1, :]) # gives the entire row at index 1
print("Entire column:\n", arr_2d[:, 2]) # gives the entire


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Specific element:
 7
Entire row:
 [5 6 7 8]
Entire column:
 [ 3  7 11]


Sorting 1d array

In [8]:
np_sort_arr = np.array([12, 3, 45, 6, 7, 89, 23])
np_sort = np.sort(np_sort_arr)
print("Original array:\n", np_sort_arr)
print("Sorted array:\n", np_sort) # gives the sorted array

Original array:
 [12  3 45  6  7 89 23]
Sorted array:
 [ 3  6  7 12 23 45 89]


Sorting 2d array

In [ ]:
np_2d_sort_arr = np.array([[12, 3, 45], [6, 7, 89], [23, 1, 34]])
np_2d_sort = np.sort(np_2d_sort_arr, axis=0) # gives the sorted array along the first axis (columns)
print("Original 2D array:\n", np_2d_sort_arr)
print("Sorted 2D array along columns:\n", np_2d_sort)


print("Sorted 2D array along rows:\n", np.sort(np_2d_sort_arr, axis=1)) # gives the sorted array along the second axis (rows)

# won't change the actual array, it will return a new sorted array
print("original 2D array:\n", np_2d_sort_arr)


Original 2D array:
 [[12  3 45]
 [ 6  7 89]
 [23  1 34]]
Sorted 2D array along columns:
 [[ 6  1 34]
 [12  3 45]
 [23  7 89]]
Sorted 2D array along rows:
 [[ 3 12 45]
 [ 6  7 89]
 [ 1 23 34]]
original 2D array:
 [[12  3 45]
 [ 6  7 89]
 [23  1 34]]


Filter

In [12]:
numbers = np.array([12, 3, 45, 6, 7, 89, 23])
filtered_numbers = numbers[numbers > 10] # gives the elements greater than 10
print("Original array:\n", numbers)

even_numbers = numbers[numbers % 2 == 0] # gives the even elements
print("Even numbers:\n", even_numbers)

odd_numbers = numbers[numbers % 2 != 0] # gives the odd elements
print("Odd numbers:\n", odd_numbers) 

Original array:
 [12  3 45  6  7 89 23]
Even numbers:
 [12  6]
Odd numbers:
 [ 3 45  7 89 23]


Filters with mask

In [14]:
mask = (numbers > 10) & (numbers < 50) # gives the elements greater than 10 and less than 50
filtered_numbers = numbers[mask]
print("Filtered numbers (greater than 10 and less than 50):\n", filtered_numbers)

Filtered numbers (greater than 10 and less than 50):
 [12 45 23]


Fancy Indexing and np.where()

In [21]:
indecies = [0, 2, 4] # gives the elements at index 0, 2 and 4
selected_numbers = numbers[indecies]
print("Selected numbers:\n", selected_numbers)


where_result = np.where(numbers > 10) # gives the indices of the elements greater than 10


print("Indices of elements greater than 10:\n", where_result)

"""
Parts:

array([0, 2, 5, 6]) → The indices where the condition (> 10) is True.
The comma (...,) → Means it's a tuple containing one array.
It's a tuple because np.where() returns one array of indices per dimension.
For a 1D array → (indices,)
For a 2D array → (row_indices, column_indices)

"""


Selected numbers:
 [12 45  7]
Indices of elements greater than 10:
 (array([0, 2, 5, 6]),)


"\nParts:\n\narray([0, 2, 5, 6]) → The indices where the condition (> 10) is True.\nThe comma (...,) → Means it's a tuple containing one array.\nIt's a tuple because np.where() returns one array of indices per dimension.\nFor a 1D array → (indices,)\nFor a 2D array → (row_indices, column_indices)\n\n"

In [22]:
condition_array = np.where(numbers>10 , numbers*2 , numbers) # gives the elements greater than 10 multiplied by 2, and the rest of the elements unchanged
print("Condition array:\n", condition_array)

Condition array:
 [ 24   3  90   6   7 178  46]


Adding and inserting(r/c) into the array

In [25]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:\n", arr1 + arr2) # element-wise addition
print("Subtraction:\n", arr1 - arr2) # element-wise subtraction

print("concatination:\n", np.concatenate((arr1, arr2))) # concatenation of two arrays

Addition:
 [5 7 9]
Subtraction:
 [-3 -3 -3]
concatination:
 [1 2 3 4 5 6]


In [26]:
original_array = np.array([[1, 2], [3, 4]])
new_array = np.array([[5, 6], [7, 8]])

new_array1 = np.vstack((original_array, new_array)) # vertical stacking of two arrays
print("Vertical stacking:\n", new_array1)

new_array2 = np.hstack((original_array, new_array)) # horizontal stacking of two arrays
print("Horizontal stacking:\n", new_array2)

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [28]:
del_array = np.array([[1, 2], [3, 4], [5, 6]])

print("Original array:\n", del_array)
print("array after deletion", np.delete(del_array, 1)) # deletes the element at index 1

print("deleted array:\n", np.delete(del_array, 1, axis=0)) # deletes the row at index 1
print("deleted array:\n", np.delete(del_array, 1, axis=1)) # deletes the column at index 1


Original array:
 [[1 2]
 [3 4]
 [5 6]]
array after deletion [1 3 4 5 6]
deleted array:
 [[1 2]
 [5 6]]
deleted array:
 [[1]
 [3]
 [5]]
